name: samba_server
description: Blazing-ly fast & highly optimized backend development framework for developing Api's & Event-Driven WebSocket's which written completely in Dart..
version: 0.0.1
repository: https://github.com/tejHackerDEV/samba_server

topics:
  - server
  - backend
  - apis
  - websockets
  - interceptors

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  mime: ^1.0.4
  slugid: ^1.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  dio: ^5.2.1+1
  web_socket_channel: ^2.4.0
